using System.IO;
using System.Text;

namespace KA.Entities.Models.Email
{
    public static class EmailForm
    {
        public static string rootPath;

        public static string FormHeadTag = "<head>"
            + "<meta http-equiv='Content-Type' content='text/html;charset=utf-8' />"
            + "<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1' />"
            + "<meta charset=\"UTF-8\">"
            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
            + "<title> K-AUCTION </title>"
            + "<style type=\"text/css\"> "
            + ".ReadMsgBody{ width: 100%; } "
            + ".ExternalClass{ width: 100%; } "
            + ".ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div { line-height: 100%; } "
            + "table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; } "
            + "img { -ms-interpolation-mode: bicubic; } "
            + "body, table, td, p, a, li, blockquote { -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; }"
            + "</style>"
            + "</head>";

        public static string FormHeaderWithSubject = "<tr>"
            + "<td style=\"width:600px; height:auto; padding:48px 0 12px 0; vertical-align:top; text-align: center; color: #000000; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size: 24px; font-weight: 700;\">K Auction</td>"
            + "</tr>"
            + "<tr>"
            + "<td style=\"width:600px;height:auto;padding:0;vertical-align:top; text-align: center; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:18px;color:#000000;font-weight:700; padding:0 0 40px 0; letter-spacing:-0.6px;\">_MAIL_SUBJECT_</td>"
            + "</tr>";

        public static string FormHeaderWithSubject2 = "<table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"600px\" bgcolor= \"#ffffff\"; style=\"padding: 32px 0 40px 0; box-sizing: border-box;  text-align: center;\">"
            + "<tr>"
            + "<td style=\"width:600px; height:auto; padding:48px 0 12px 0; vertical-align:top; text-align: center; color: #000000; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size: 24px; font-weight: 700;\">K Auction</td>"
            + "</tr>"
            + "<tr>"
            + "<td style=\"width:600px;height:auto;padding:0;vertical-align:top; text-align: center; font-family: Malgun Gothic, sans-serif; font-size:18px;color:#000000;font-weight:700; padding:0 0 40px 0; letter-spacing:-0.6px;\">_MAIL_SUBJECT_</td>"
            + "</tr>"
            + "</table>";

        public static string FormFooter = "<tr>"
            + "<td bgcolor=\"#666666\" style=\"width:600px;height:auto; vertical-align:top; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:11px; line-height:2em;  padding: 10px 0 32px 0; color: #ffffff;\">"
            + "_MAIL_FOOTER_"
            + "</td>"
            + "</tr>";

        public static string FormFooter2 = "<table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"600\" bgcolor= \"#ffffff\" style=\"padding: 32px 0 40px 0; box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td bgcolor=\"#666666\" style=\"width:600px;height:auto; vertical-align:top; font-family: Malgun Gothic, sans-serif; font-size:14px; line-height:2em;  padding: 10px 0 32px 0; color: #ffffff;\">_MAIL_FOOTER_</td>"
            + "</tr>"
            + "</table>";

        public static string FormDefault = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">"
            + FormHeadTag
            + "<body>"
            + "<div align=\"center\";>"
            + "<table width=\"auto\" cellpadding=\"0\" bgcolor= \"#ffffff\"; cellspacing=\"0\" style=\"padding: 32px 40px; box-sizing: border-box;  text-align: center;\">"
            + FormHeaderWithSubject
            + "<tr>"
            + "<td background=\"_SERVICE_DOMAIN_/images/email/img_k_mid.jpg\" style=\"width:600px;padding:0 0 20px 0;vertical-align:top; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:12px;color:#666666;line-height:1.8em;text-align: left; display: inline-block;\">_MAIL_BODY_</td>"
            + "</tr>"
            + "<tr><td style=\"padding-bottom: 35px;\"></td></tr>"
            + FormFooter
            + "</table>"
            + "</div>"
            + "</body>"
            + "</html>";

        public static string FormFindPassword = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">"
            + FormHeadTag
            + "<body>"
            + "<div align=\"center\";>"
            + "<table width=\"auto\" cellpadding=\"0\" bgcolor= \"#ffffff\"; cellspacing=\"0\" style=\"padding: 32px 40px; box-sizing: border-box;  text-align: center;\">"
            + FormHeaderWithSubject
            + "<tr>"
            + "<td background=\"_SERVICE_DOMAIN_/images/email/img_k_mid.jpg\" style=\"width:600px;padding:0 0 20px 0;vertical-align:top; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:12px;color:#666666;line-height:1.8em;text-align: left; display: inline-block;\">_MAIL_BODY_</td>"
            + "</tr>"
            + "<tr>"
            + "<td bgcolor=\"#f9f9f9\" style=\"width: 600px; padding: 12px 20px;  color: #000000; font-family: 'Noto Sans KR', sans-serif; font-weight: 700; text-align: left; display: inline-block; box-sizing:border-box;\">"
            + "_ETC1_"
            + "</td>"
            + "</tr>"
            + "<tr><td style=\"padding-bottom: 35px;\"></td></tr>"
            + FormFooter
            + "</table>"
            + "</div>"
            + "</body>"
            + "</html>";

        public static string FormEmailVerificationKr = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">"
            + FormHeadTag
            + "<body>"
            + "<div align=\"center\";>"
            + "<table width=\"auto\" cellpadding=\"0\" bgcolor= \"#ffffff\"; cellspacing=\"0\" style=\"padding: 32px 40px; box-sizing: border-box;  text-align: center;\">"
            + FormHeaderWithSubject
            + "<tr>"
            + "<td background=\"_SERVICE_DOMAIN_/images/email/img_k_mid.jpg\" style=\"width:600px;padding:0 0 20px 0;vertical-align:top; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:12px;color:#666666;line-height:1.8em;text-align: left; display: inline-block;\">_MAIL_BODY_</td>"
            + "</tr>"

            + "<tr>"
            + "<td style=\"text-align: left;width:600px;padding:10px 0 10px 0;vertical-align:top; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:12px; font-weight: 600;\">인증번호</td>"
            + "</tr>"
            
            + "<tr>"
            + "<td bgcolor=\"#f9f9f9\" style=\"font-size: 24px; height: 80px; width: 600px; padding-top: 20px; color: #000000; font-family: 'Noto Sans KR', sans-serif; font-weight: 700; text-align: center; display: inline-block; box-sizing:border-box;\">"
            + "_ETC1_"
            + "</td>"
            + "</tr>"

            + "<tr>"
            + "<td style=\"text-align: left;width:600px;padding:10px 0 10px 0;vertical-align:top; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:12px; font-weight: 600;\">이용 안내</td>"
            + "</tr>"

            + "<tr>"
            + "<td bgcolor=\"#f9f9f9\" style=\"width: 600px; height: 100px; padding: 0px 20px;  color: #000000; font-family: 'Noto Sans KR', sans-serif; text-align: left; display: inline-block; box-sizing:border-box;\">"
            + "<div style=\"height: 20px;\"><span>·</span><p style=\"display: inline-block; padding: 10px 0 10px 5px; font-size: 12px;\">인증이 완료되기 전까지 홈페이지의 인증 팝업은 닫지 말아주세요.</p></div>"
            + "<div style=\"height: 20px;\"><span>·</span><p style=\"display: inline-block; padding: 10px 0 10px 5px; font-size: 12px;\">인증 후 남은 가입 절차를 진행하시기 바랍니다.</p></div>"
            + "<div style=\"height: 20px;\"><span>·</span><p style=\"display: inline-block; padding: 10px 0 10px 5px; font-size: 12px;\">가입 입력 정보 중 별도의 신분(기관)확인 절차가 있을 수 있으니 안내를 따라 주시기 바랍니다.</p></div>"
            + "</td>"
            + "</tr>"

            + "<tr><td style=\"padding-bottom: 35px;\"></td></tr>"
            + FormFooter
            + "</table>"
            + "</div>"
            + "</body>"
            + "</html>";

        public static string FormEmailVerificationEn = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">"
            + FormHeadTag
            + "<body>"
            + "<div align=\"center\";>"
            + "<table width=\"auto\" cellpadding=\"0\" bgcolor= \"#ffffff\"; cellspacing=\"0\" style=\"padding: 32px 40px; box-sizing: border-box;  text-align: center;\">"
            + FormHeaderWithSubject
            + "<tr>"
            + "<td background=\"_SERVICE_DOMAIN_/images/email/img_k_mid.jpg\" style=\"width:600px;padding:0 0 20px 0;vertical-align:top; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:12px;color:#666666;line-height:1.8em;text-align: left; display: inline-block;\">_MAIL_BODY_</td>"
            + "</tr>"

            + "<tr>"
            + "<td style=\"text-align: left;width:600px;padding:10px 0 20px 0;vertical-align:top; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:12px;\">Verfication Code</td>"
            + "</tr>"

            + "<tr>"
            + "<td bgcolor=\"#f9f9f9\" style=\"font-size: 24px; height: 80px; width: 600px; padding-top: 20px; color: #000000; font-family: 'Noto Sans KR', sans-serif; font-weight: 700; text-align: center; display: inline-block; box-sizing:border-box;\">"
            + "_ETC1_"
            + "</td>"
            + "</tr>"

            + "<tr>"
            + "<td style=\"text-align: left;width:600px;padding:10px 0 20px 0;vertical-align:top; font-family: 'Noto Sans KR', '맑은고딕', Malgun Gothic, sans-serif; font-size:12px;\">User Guide</td>"
            + "</tr>"

            + "<tr>"
            + "<td bgcolor=\"#f9f9f9\" style=\"width: 600px; height: 120px; padding: 10px 20px;  color: #000000; font-family: 'Noto Sans KR', sans-serif; text-align: left; display: inline-block; box-sizing:border-box;\">"
            + "<div><span>·</span><p style=\"display: inline; padding: 10px 0 10px 5px; font-size: 12px;\">Please do not close the verification pop-up window on the registration page until verification is complete.</p></div>"
            + "<div><span>·</span><p style=\"display: inline; padding: 10px 0 10px 5px; font-size: 12px;\">Please continue with the rest of the registration process after email verification.</p></div>"
            + "<div><span>·</span><p style=\"display: inline; padding: 10px 0 10px 5px; font-size: 12px;\">Please note that additional identity or organization verification may be required for member registration. Please follow the instructions on the registration page.</p></div>"
            + "</td>"
            + "</tr>"

            + "<tr><td style=\"padding-bottom: 35px;\"></td></tr>"
            + FormFooter
            + "</table>"
            + "</div>"
            + "</body>"
            + "</html>";


        public static string FormConsign = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">"
            + FormHeadTag
            + "<body style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly;\" style='font-family:Malgun Gothic; font-size:12px;'>"
            + "<div align=\"center\">"
            + FormHeaderWithSubject2
            + "<table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"600\" bgcolor=\"#ffffff\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">신청인 정보</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이름</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{NAME}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">회원번호</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{UID}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">주소</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{ADDRESS}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이동전화</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{MOBILE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이메일</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{EMAIL}</td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"
            + "<table width=\"600\" cellpadding=\"0\" bgcolor=\"#ffffff\" cellspacing=\"0\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">위탁작품 정보</td></tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작가명</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{ARTIST}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작품명</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{TITLE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작품재료</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{MATERIAL}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작품크기</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{SIZE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">에디션</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{EDITION}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">제작연도</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{MAKEDATE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">출처</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{DESC}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">기타</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{ETC}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">구입가</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{PRICE_PURCHASE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">희망가</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{PRICE_DESIRED}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작품 이미지</td>"
            + "<td style=\"padding: 8px 0 8px 0;\"><div align=\"center\">{IMAGES}</div></td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"
            
            + "<table width=\"600\" cellpadding=\"0\" bgcolor=\"#ffffff\" cellspacing=\"0\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">수신확인 처리</td></tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">수신확인</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\"><a href='{SERVICE_DOMAIN}/Consign/{CONSIGN_UID}' target='_blank'>처리</a></td>"
            + "</tr>"
            + "</table>"

            + FormFooter2
            + "</div>"
            + "</body>"
            + "</html>";

        public static string FormConsignAdminReview = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">"
            + FormHeadTag
            + "<body style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly;\" style='font-family:Malgun Gothic; font-size:12px;'>"
            + "<div align=\"center\">"
            + FormHeaderWithSubject2
            + "<table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"600\" bgcolor=\"#ffffff\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">신청인 정보</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">위탁 번호</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{CONSIGN_UID}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이름</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{NAME}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">회원번호</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{UID}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">주소</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{ADDRESS}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이동전화</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{MOBILE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이메일</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{EMAIL}</td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"

            + "<table width=\"600\" cellpadding=\"0\" bgcolor=\"#ffffff\" cellspacing=\"0\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">검토상태</td></tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">적합여부</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{RECEIPT_YN}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">권고가</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{RECOMMENDED_PRICE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">메모(내부용)</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{MEMO}</td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"

            + "<table width=\"600\" cellpadding=\"0\" bgcolor=\"#ffffff\" cellspacing=\"0\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">위탁작품 정보</td></tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작가명</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{ARTIST}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작품명</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{TITLE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작품재료</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{MATERIAL}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작품크기</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{SIZE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">에디션</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{EDITION}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">제작연도</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{MAKEDATE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">출처</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{DESC}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">기타</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{ETC}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">구입가</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{PRICE_PURCHASE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">희망가</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{PRICE_DESIRED}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">작품 이미지</td>"
            + "<td style=\"padding: 8px 0 8px 0;\"><div align=\"center\">{IMAGES}</div></td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"

            + FormFooter2
            + "</div>"
            + "</body>"
            + "</html>";

        public static string FormApplyBook = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">"
            + "<body style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly;\" style='font-family:Malgun Gothic; font-size:12px;'>"
            + "<div align=\"center\">"
            + FormHeaderWithSubject2
            + "<table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"600\" bgcolor=\"#ffffff\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">신청인 정보</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이름</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{NAME}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">회원번호</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{UID}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">주소</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{ADDRESS}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이동전화</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{MOBILE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이메일</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{EMAIL}</td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"
            + "<table width=\"600\" cellpadding=\"0\" bgcolor=\"#ffffff\" cellspacing=\"0\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">구독 정보</td></tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">구독 주소지</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{APPLY_BOOK_ADDRESS}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">구독자 이름</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{APPLY_BOOK_NAME}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">구독자 연락처</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:70%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{APPLY_BOOK_MOBILE}</td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"
            + "</div>"
            + "</body>"
            + "</html>";

        public static string FormApplyBookComplete = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">"
            + "<body style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly;\" style='font-family:Malgun Gothic; font-size:12px;'>"
            + "<div align=\"center\">"
            + FormHeaderWithSubject2
            + "<table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"600\" bgcolor=\"#ffffff\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"4\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; font-weight: bold;\">"
            + "{NAME}님, 안녕하세요.<br /><br />"
            + "케이옥션 도록 정기 구독료 입금이 확인되어 익월부터 도록이 발송될 예정입니다.<br />"
            + "아래 신청내용 확인하시고 조정이 필요한 경우 담당자에게 문의하시기 바랍니다.<br /><br />"
            + "</td>"
            + "</tr>"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:300px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">신청인 정보</td>"
            + "<td colspan=\"2\" style=\"width:300px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">구독 정보</td></tr>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">이름</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{NAME}</td>"
            + "<td bgcolor=\"#efefef\" rowspan=\"3\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">배송지</td>"
            + "<td bgcolor=\"#ffffff\" rowspan=\"3\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{APPLY_BOOK_ADDRESS}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">회원 ID</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{ID}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">신청일시</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{REG_DATE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">입금 확인일</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{APPLY_DATE}</td>"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">구독기간</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{PERIOD}</td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"

            + "<table width=\"600\" cellpadding=\"0\" bgcolor=\"#ffffff\" cellspacing=\"0\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">구독 안내</td>" 
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"text-align: left; width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 12px; padding: 6px 6px 6px 6px; font-weight: bold;\">"
            + " - 구독 기간은 입금일 기준이며 익월부터 12개월간 매 월1회 발송 됩니다.<br />"
            + " - 배송지 이전 시 반드시 마이페이지에서 구독 배송정보를 수정하시기 바랍니다."
            + "</td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"
            + "</div>"
            + "</body>"
            + "</html>";

        public static string FormApplyBookCompleteEn = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">"
            + "<body style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly;\" style='font-family:Malgun Gothic; font-size:12px;'>"
            + "<div align=\"center\">"
            + FormHeaderWithSubject2
            + "<table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"600\" bgcolor=\"#ffffff\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td colspan=\"4\" style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; font-weight: bold;\">"
            + "Dear {NAME},<br /><br />"
            + "You have successfully subscribed for the K Auction monthly catalogue, and the shipment of the catalogue will begin next month.<br />"
            + "Please review your subscription details below. For any inquiries regarding your subscription, please contact your sales representative. <br /><br />"
            + "</td>"
            + "</tr>"
            + "<tr>"
            + "<td colspan=\"2\" style=\"width:300px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">Subscriber Information</td>"
            + "<td colspan=\"2\" style=\"width:300px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">Subscription Details</td></tr>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">Name</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{NAME}</td>"
            + "<td bgcolor=\"#efefef\" rowspan=\"3\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">Shipment Address</td>"
            + "<td bgcolor=\"#ffffff\" rowspan=\"3\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{APPLY_BOOK_ADDRESS}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">Member ID</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{ID}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">Subscription Date</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{REG_DATE}</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">Date of Payment</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{APPLY_DATE}</td>"
            + "<td bgcolor=\"#efefef\" style=\"width:15%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 0; font-weight: bold;\">Subscription Period</td>"
            + "<td bgcolor=\"#ffffff\" style=\"width:35%;color: #666666; font-family: Malgun Gothic, sans-serif; font-size: 14px; padding: 6px 0 6px 22px; text-align: left;\">{PERIOD}</td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"

            + "<table width=\"600\" cellpadding=\"0\" bgcolor=\"#ffffff\" cellspacing=\"0\" style=\"box-sizing: border-box; text-align: center;\">"
            + "<tr>"
            + "<td style=\"width:600px; height:auto; vertical-align:top; padding: 0 0 8px 0; text-align: left; color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 16px; font-weight: 700;\">Subscription Information</td>"
            + "</tr>"
            + "<tr style=\"mso-border-top-alt: 1px solid #cccccc; mso-border-bottom-alt: 1px solid #cccccc; border-top: 1px solid #cccccc; border-bottom: 1px solid #cccccc;\">"
            + "<td bgcolor=\"#efefef\" style=\"text-align: left; width:30%;color: #000000; font-family: Malgun Gothic, sans-serif; font-size: 12px; padding: 6px 6px 6px 6px; font-weight: bold;\">"
            + " - The catalogue shipment begins the month after the date of payment and will be shipped once a month for a duration of twelve months.<br />"
            + " - Please make sure your address is up to date before the day of shipment by going to My Page > Catalogue Subscription Address."
            + "</td>"
            + "</tr>"
            + "<tr><td style=\"padding: 0 0 40px 0;\"></td></tr>"
            + "</table>"
            + "</div>"
            + "</body>"
            + "</html>";
    }
}
