//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KA.Web.Public.Resources.Views.Shared._Partial {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _AddressModalPartial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _AddressModalPartial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KA.Web.Public.Resources.Views.Shared._Partial._AddressModalPartial", typeof(_AddressModalPartial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 제외한 숫자만 입력.
        /// </summary>
        internal static string @__제외한_숫자만_입력 {
            get {
                return ResourceManager.GetString("- 제외한 숫자만 입력", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 국가.
        /// </summary>
        internal static string 국가 {
            get {
                return ResourceManager.GetString("국가", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 받는사람.
        /// </summary>
        internal static string 받는사람 {
            get {
                return ResourceManager.GetString("받는사람", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 받는사람을 입력하세요..
        /// </summary>
        internal static string 받는사람을_입력하세요_ {
            get {
                return ResourceManager.GetString("받는사람을 입력하세요.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상세주소.
        /// </summary>
        internal static string 상세주소 {
            get {
                return ResourceManager.GetString("상세주소", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 상세주소를 입력하세요..
        /// </summary>
        internal static string 상세주소를_입력하세요_ {
            get {
                return ResourceManager.GetString("상세주소를 입력하세요.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연락처.
        /// </summary>
        internal static string 연락처 {
            get {
                return ResourceManager.GetString("연락처", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연락처를 입력하세요..
        /// </summary>
        internal static string 연락처를_입력하세요_ {
            get {
                return ResourceManager.GetString("연락처를 입력하세요.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 우편번호.
        /// </summary>
        internal static string 우편번호 {
            get {
                return ResourceManager.GetString("우편번호", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 우편번호를 입력하세요..
        /// </summary>
        internal static string 우편번호를_입력하세요_ {
            get {
                return ResourceManager.GetString("우편번호를 입력하세요.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자택.
        /// </summary>
        internal static string 자택 {
            get {
                return ResourceManager.GetString("자택", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주소.
        /// </summary>
        internal static string 주소 {
            get {
                return ResourceManager.GetString("주소", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주소 검색.
        /// </summary>
        internal static string 주소_검색 {
            get {
                return ResourceManager.GetString("주소 검색", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주소 등록/수정.
        /// </summary>
        internal static string 주소_등록_수정 {
            get {
                return ResourceManager.GetString("주소 등록/수정", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주소명.
        /// </summary>
        internal static string 주소명 {
            get {
                return ResourceManager.GetString("주소명", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주소입력.
        /// </summary>
        internal static string 주소입력 {
            get {
                return ResourceManager.GetString("주소입력", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 직장.
        /// </summary>
        internal static string 직장 {
            get {
                return ResourceManager.GetString("직장", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 직접입력.
        /// </summary>
        internal static string 직접입력 {
            get {
                return ResourceManager.GetString("직접입력", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 직접입력 주소를 입력하세요..
        /// </summary>
        internal static string 직접입력_주소를_입력하세요_ {
            get {
                return ResourceManager.GetString("직접입력 주소를 입력하세요.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        internal static string 취소 {
            get {
                return ResourceManager.GetString("취소", resourceCulture);
            }
        }
    }
}
