//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KA.Web.Public.Resources.Views.Shared._Partial {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _CertificateDocumentGuide {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _CertificateDocumentGuide() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KA.Web.Public.Resources.Views.Shared._Partial._CertificateDocumentGuide", typeof(_CertificateDocumentGuide).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 고유식별 정보가 가려지지 않은 증빙서류는&lt;br/&gt; 반려될 수 있으니 유의하시기 바랍니다..
        /// </summary>
        internal static string 고유식별_정보가_가려지지_않은_증빙서류는_br___반려될_수_있으니_유의하시기_바랍니다_ {
            get {
                return ResourceManager.GetString("고유식별 정보가 가려지지 않은 증빙서류는<br/> 반려될 수 있으니 유의하시기 바랍니다.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내국인의 경우.
        /// </summary>
        internal static string 내국인의_경우 {
            get {
                return ResourceManager.GetString("내국인의 경우", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 신분증 촬영 시 안내된 부분을 &lt;span&gt;가리고 찍거나,&lt;/span&gt;&lt;br/&gt;이미 촬영한 경우 &lt;span&gt;불필요한 정보를 가려주세요.&lt;/span&gt;.
        /// </summary>
        internal static string 신분증_촬영_시_안내된_부분을__span_가리고_찍거나___span__br__이미_촬영한_경우__span_불필요한_정보를_가려주세요___span_ {
            get {
                return ResourceManager.GetString("신분증 촬영 시 안내된 부분을 <span>가리고 찍거나,</span><br/>이미 촬영한 경우 <span>불필요한 정보를 가려주세요.</span>" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 여권번호 및 성별, 국가 등 정보.
        /// </summary>
        internal static string 여권번호_및_성별__국가_등_정보 {
            get {
                return ResourceManager.GetString("여권번호 및 성별, 국가 등 정보", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 외국인의 경우.
        /// </summary>
        internal static string 외국인의_경우 {
            get {
                return ResourceManager.GetString("외국인의 경우", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 운전면허번호 및&lt;br/&gt;주민등록번호 뒷자리.
        /// </summary>
        internal static string 운전면허번호_및_br__주민등록번호_뒷자리 {
            get {
                return ResourceManager.GetString("운전면허번호 및<br/>주민등록번호 뒷자리", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 주민등록번호 뒷자리.
        /// </summary>
        internal static string 주민등록번호_뒷자리 {
            get {
                return ResourceManager.GetString("주민등록번호 뒷자리", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인.
        /// </summary>
        internal static string 확인 {
            get {
                return ResourceManager.GetString("확인", resourceCulture);
            }
        }
    }
}
