//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KA.Web.Public.Resources.Views.Shared._Partial {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _WorkInquiryModalPartial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _WorkInquiryModalPartial() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KA.Web.Public.Resources.Views.Shared._Partial._WorkInquiryModalPartial", typeof(_WorkInquiryModalPartial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   1,000자 제한과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _1_000자_제한 {
            get {
                return ResourceManager.GetString("1,000자 제한", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기타과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 기타 {
            get {
                return ResourceManager.GetString("기타", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내용을 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 내용을_입력하세요_ {
            get {
                return ResourceManager.GetString("내용을 입력하세요.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   담당자 연락처과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 담당자_연락처 {
            get {
                return ResourceManager.GetString("담당자 연락처", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문의내용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 문의내용 {
            get {
                return ResourceManager.GetString("문의내용", resourceCulture);
            }
        }
        
        /// <summary>
        ///   문의유형을 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 문의유형을_선택하세요 {
            get {
                return ResourceManager.GetString("문의유형을 선택하세요", resourceCulture);
            }
        }
        
        /// <summary>
        ///   응찰 관련 문의과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 응찰_관련_문의 {
            get {
                return ResourceManager.GetString("응찰 관련 문의", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작품 문의하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 작품_문의하기 {
            get {
                return ResourceManager.GetString("작품 문의하기", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작품정보 관련 문의과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 작품정보_관련_문의 {
            get {
                return ResourceManager.GetString("작품정보 관련 문의", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재문의하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 재문의하기 {
            get {
                return ResourceManager.GetString("재문의하기", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제출하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 제출하기 {
            get {
                return ResourceManager.GetString("제출하기", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨디션 관련 문의과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 컨디션_관련_문의 {
            get {
                return ResourceManager.GetString("컨디션 관련 문의", resourceCulture);
            }
        }
    }
}
